#!/usr/bin/env python3
"""Generate sio/thaysen_data.sio from the Thaysen strain workbook.

Marshalling only: it moves published values into Sounio source and computes
nothing. The viable-fraction calculation lives in the engine, not here.

The six rows whose reported optimum lies outside their own reported bounds are
EXCLUDED by name, not repaired -- see data/README.md. A strain is included for a
given field only if that field has at least one numeric bound; a strain with no
bound is counted as unreported for that field, never as tolerant of everything.

Emits a provenance header carrying the source DOI and the sha256 of the workbook
it was generated from, and a runtime check that the strain count matches. A
generated file whose hash does not match its source is refused rather than used.

Usage:
    python3 tools/gen_thaysen_envelopes.py \
        data/thaysen-strains/hydrogen-utilizing-microbial-strains.xlsx \
        > sio/thaysen_data.sio
"""
import hashlib
import subprocess
import sys
import os

# Rows that contradict their own bounds. Excluded, named, not repaired.
EXCLUDED = {
    "Desulfonatronum buryatense Su2",
    "Methanofollis aquaemaris",
    "Methanogenium tatii",
    "Methanosarcina spelaei",
    "Methanobacterium aarhusense",
    "Methanotorris igneus",
}

FIELDS = [("Temp", "Temp_LOW", "Temp_UP"),
          ("Salt", "Salt_LOW (g/L)", "Salt_UP (g/L)"),
          ("pH", "pH_LOW", "pH_UP")]


def num(s):
    try:
        return float((s or "").strip().replace(",", "."))
    except ValueError:
        return None


def main():
    book = sys.argv[1]
    here = os.path.dirname(os.path.abspath(__file__))
    tsv = subprocess.run(
        [sys.executable, os.path.join(here, "xlsx_to_tsv.py"), book,
         "--sheet", "all info"],
        capture_output=True, text=True, check=True).stdout

    sha = hashlib.sha256(open(book, "rb").read()).hexdigest()
    rows = [l.split("\t") for l in tsv.rstrip("\n").split("\n")]
    hdr = [h.strip() for h in rows[0]]
    idx = {h: i for i, h in enumerate(hdr)}

    def cell(r, c):
        i = idx[c]
        return (r[i] if i < len(r) else "").strip()

    recs, excluded_seen = [], set()
    for r in rows[1:]:
        if not (r and r[0].strip()):
            continue
        name = r[0].strip()
        if name in EXCLUDED:
            excluded_seen.add(name)
            continue
        grp = {"METH": 0, "SRB": 1, "ACET": 2}.get(cell(r, "microbe").strip())
        if grp is None:
            continue
        vals = []
        for _, lo, up in FIELDS:
            vals.append((num(cell(r, lo)), num(cell(r, up))))
        recs.append((grp, vals))

    missing = EXCLUDED - excluded_seen
    if missing:
        sys.exit(f"FAIL: excluded rows not found in the source: {sorted(missing)}\n"
                 "The workbook changed; the exclusion list must be re-derived.")

    n = len(recs)
    L = []
    L.append("// GENERATED by tools/gen_thaysen_envelopes.py -- do not edit.")
    L.append("//")
    L.append("// Source: Thaysen et al., DOI 10.17632/4dksb2x4zn.1, CC BY, sheet 'all info'")
    L.append(f"// Workbook sha256: {sha}")
    L.append(f"// Strains emitted: {n} of 518. Six rows whose reported optimum lies")
    L.append("// outside their own reported bounds are EXCLUDED by name, not repaired:")
    for e in sorted(EXCLUDED):
        L.append(f"//   {e}")
    L.append("//")
    L.append("// A bound of -999.0 means UNREPORTED for that field. It is never treated")
    L.append("// as tolerance of everything: a strain with no bound is excluded from the")
    L.append("// denominator for that field, so a viable fraction is always a fraction")
    L.append("// of the strains that actually reported.")
    L.append("")
    L.append(f"pub var TH_N: i64 = {n}")
    L.append("")

    def arr(name, vals, fmt):
        out = [f"pub var {name}: [{'f64' if fmt else 'i64'}; {n}] = "
               f"[{'0.0' if fmt else '0'}; {n}]"]
        return out, vals

    L.append(f"pub var TH_GROUP: [i64; {n}] = [0; {n}]")
    for f in ("TH_T_LO", "TH_T_UP", "TH_S_LO", "TH_S_UP", "TH_PH_LO", "TH_PH_UP"):
        L.append(f"pub var {f}: [f64; {n}] = [0.0; {n}]")
    L.append("")
    L.append("pub fn thaysen_init() with Mut {")
    for i, (grp, vals) in enumerate(recs):
        L.append(f"    TH_GROUP[{i}] = {grp}")
        for (fname, (lo, up)) in zip(("T", "S", "PH"), vals):
            for suff, v in (("LO", lo), ("UP", up)):
                if v is None:
                    lit = "0.0 - 999.0"
                elif v < 0:
                    lit = f"0.0 - {abs(v)!r}"
                else:
                    lit = repr(v)
                L.append(f"    TH_{fname}_{suff}[{i}] = {lit}")
    L.append("}")
    print("\n".join(L))
    print(f"\n// emitted {n} strains", file=sys.stderr)


if __name__ == "__main__":
    main()
